// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lopdtjxlaojdybraxqvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvcGR0anhsYW9qZHlicmF4cXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTI1NDgsImV4cCI6MjA2MjI2ODU0OH0.I3wnQkLyEeOAq9wEz-Xx75tvzlpndr-_RjXLijY5kpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);